<a href="https://colab.research.google.com/github/surya1307/The-sparks-Foundation/blob/main/ML_linear_pickle%26_joblib_reg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
canada=pd.read_csv('https://raw.githubusercontent.com/Rhevathi/DATA-SCIENCE/master/ML/1_linear_reg/Exercise/canada_per_capita_income.csv')
canada

year  per capita income (US$)
0   1970              3399.299037
1   1971              3768.297935
2   1972              4251.175484
3   1973              4804.463248
4   1974              5576.514583
5   1975              5998.144346
6   1976              7062.131392
7   1977              7100.126170
8   1978              7247.967035
9   1979              7602.912681
10  1980              8355.968120
11  1981              9434.390652
12  1982              9619.438377
13  1983             10416.536590
14  1984             10790.328720
15  1985             11018.955850
16  1986             11482.891530
17  1987             12974.806620
18  1988             15080.283450
19  1989             16426.725480
20  1990             16838.673200
21  1991             17266.097690
22  1992             16412.083090
23  1993             15875.586730
24  1994             15755.820270
25  1995             16369.317250
26  1996             16699.826680
27  1997             17310.757750
28  1998             16622.671870
29  1999             17581.024140
30  2000             18987.382410
31  2001             18601.397240
32  2002             19232.175560
33  2003             22739.426280
34  2004             25719.147150
35  2005             29198.055690
36  2006             32738.262900
37  2007             36144.481220
38  2008             37446.486090
39  2009             32755.176820
40  2010             38420.522890
41  2011             42334.711210
42  2012             42665.255970
43  2013             42676.468370
44  2014             41039.893600
45  2015             35175.188980
46  2016             34229.193630

In [3]:
canada.columns

Index(['year', 'per capita income (US$)'], dtype='object')

In [4]:
canada.columns=canada.columns.str.strip()
canada.columns

Index(['year', 'per capita income (US$)'], dtype='object')

In [5]:
canada.columns=canada.columns.str.replace(' ','_')
canada.columns

Index(['year', 'per_capita_income_(US$)'], dtype='object')

In [6]:
canada.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 2 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   year                     47 non-null     int64  
 1   per_capita_income_(US$)  47 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 880.0 bytes


In [7]:
reg=linear_model.LinearRegression()

In [8]:
x=canada.drop(['per_capita_income_(US$)'],axis=1)
y=canada['per_capita_income_(US$)']

In [9]:
reg.fit(x,y)

LinearRegression()

In [10]:
reg.predict([[2020]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([41288.69409442])

In [11]:
reg.coef_

array([828.46507522])

In [12]:
reg.intercept_

-1632210.7578554575

In [13]:
import pickle

In [14]:
with open('reg_pickle','wb') as f:
  pickle.dump(reg,f)

In [15]:
with open('reg_pickle','rb') as f:
  sreg=pickle.load(f)

In [16]:
sreg.predict([[2020]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([41288.69409442])

In [17]:
import joblib

In [18]:
joblib.dump(reg,'reg_joblib')

['reg_joblib']

In [19]:
nj=joblib.load('reg_joblib')

In [20]:
nj.predict([[2020]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([41288.69409442])